version: "3.7"

services:
  clownbot:
    container_name: ClownBotContainer
    image: ghcr.io/clownbot
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        SERVICE_NAME: clownbot
        EXPOSED_PORT: 8080
        DATABASE_HOST: postgres_db