version: "3.7"

services:
  clownbot:
    container_name: ClownBotContainer
    image: ghcr.io/dawist-o/dailyclownbot
    build:
      context: ./
      dockerfile: ./Dockerfile
#      Это аргументы для билда, которые в Dockerfile
#      сюда например можно указать версию
      args:
        SERVICE_NAME: clownbot
        EXPOSED_PORT: 8080
        HELLO_WORLD: Hello World, it's argument from compose in Dockerfile!