name: ClownBot

on:
  push:
    branches:
      - master
      - "hotfix-*"

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: development
    steps:
      - uses: actions/checkout@v2
        with:
          detch-depth: 0
      - name: Login to GHCR
        run: echo ${{ secrets.ACTION_TOKEN }} | docker login ghcr.io -u dawist-o --password-stdin
      - name: Set backend build properties
        run: echo -n ${{ secrets.BACKEND_BUILD_PROPS }} > src/main/resources/application.yml
#    try this    run: echo -n ${{ secrets.FRONTEND_BUILD_DOTENV }} | base64 -d > services/frontend/.env
      - name: Pull all already existing images
        # to make this work we have to set build versions from build.gradle.kts file
        # The exit code is always mapped to 0, as for some reason docker-compose pull likes to exit with a non-zero values
        # even when --ignore-pull-failures is set
        run: docker-compose -f build.docker-compose.yml pull --ignore-pull-failures || true
      - name: Build bot and database images
        run: |
          docker-compose -f build.docker-compose.yml up
          docker-compose -f build.docker-compose.yml down
      # build images and then stop, because we only need the build image and we don't need it to be running
      # we check if image with same version exists (from pull) then we don't rebuild it
      - name: Push images to GHCR
        run: docker-compose -f build.docker-compose.yml push